spring.application.name=javaTrainer

#PSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/example
#spring.datasource.username=iliag
#spring.datasource.password=12345678
#spring.datasource.driver-class-name=org.postgresql.Driver

#PSQL FOR DEPLOY
spring.datasource.url=jdbc:postgresql://dpg-d9gir537uimc738epa5g-a.oregon-postgres.render.com:5432/java_trainer_db?sslmode=require
spring.datasource.username=java_trainer_db_user
spring.datasource.password=nHk38S8hHLAViC8Gf7hto8noFFsC5Mta
spring.datasource.driver-class-name=org.postgresql.Driver
#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#TelegramBot
telegram.bot.username=LeptoppolisTrainerBot
telegram.bot.token=8532252151:AAHEvCiQuNVOkJ1p7Tq11IajSotMpl8d768
spring.jvm.options=-Djava.net.preferIPv4Stack=true
spring.jvm.options=-Dhttps.proxyHost=cluster-node1.mosline.ru -Dhttps.proxyPort=443